# Install docker CE on linux (ubuntu and redhat)
---
- hosts: "{{ computer_name }}"
  tasks:
  
  - name: Install prerequisites for Docker repository on Ubuntu 
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
      update_cache: yes
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Install Docker CE on Ubuntu 
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      update_cache: yes
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Install prerequisites for docker-compose
    apt:
      name: ['python3-pip', 'python3-setuptools', 'virtualenv']
    when: ansible_facts['distribution'] == "Ubuntu"

  #- name: Install docker-compose
  #  pip:
  #    name: docker-compose

  - name: Install Docker prerequisites on RHEL or CentOS 
    yum:
      name: 
        - yum-utils 
        - python3-pip
        - python3-setuptools 
      state: present
    when: ansible_facts['os_family'] == "RedHat"

  - name: add docker repo for RHEL or CentOS 
    get_url: 
      url: https://download.docker.com/linux/centos/docker-ce.repo 
      dest: /etc/yum.repos.d/docker-ce.repo
    when: ansible_facts['os_family'] == "RedHat"

  - name: Install Docker on RHEL or CentOS 
    yum: 
      name: 
        - docker-ce 
        - docker-ce-cli
        - containerd.io 
      state: present 
    when: ansible_facts['os_family'] == "RedHat"

  - name: Enable and Start Docker Service
    service: 
      name: docker 
      state: started
      enabled: yes   
  
#  - name: Install docker-compose
#    pip:
#      name: docker-compose
#      executable: pip3.6 